import { Account, PlanItem, CreditCard, Debt, Goal, Transaction } from './types';

export const FX_RATES = {
  COP: 1,
  USD: 4200, // 1 USD = 4200 COP
  EUR: 4600, // 1 EUR = 4600 COP
};

// Simple dictionary implementation for demo
export const TRANSLATIONS = {
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.history': 'History',
    'nav.analytics': 'Analytics',
    'nav.accounts': 'Accounts',
    'nav.debts': 'Risk & Debts',
    'nav.goals': 'Goals',
    'nav.planner': 'Planner',
    'nav.settings': 'Settings',
    'nav.ai': 'AI Assistant',
    // Dashboard
    'dash.total': 'Total Balance',
    'dash.available': 'Available Liquidity',
    'dash.relative': 'Relative Balance',
    'dash.recent': 'Data Stream',
    'dash.targets': 'Targets',
    'dash.risk': 'Risk Assessment',
    'dash.feedback': 'Feedback',
    'dash.feedback.placeholder': 'Write your comment, report a bug, or request a feature...',
    'dash.feedback.send': 'Send',
    'dash.feedback.success': 'Feedback sent! Thank you.',
    'dash.feedback.error': 'Could not send feedback. Try again.',
    'dash.feedback.teaser': 'Comments or suggestions?',
    'dash.burn': 'Monthly Burn Rate',
    'dash.commands': 'Quick Commands',
    // Actions
    'act.quick_input': 'Quick Input',
    'act.create_ai': 'Create with AI',
    'act.add': 'Add',
    'act.save': 'Save Record',
    'act.confirm_create': 'Confirm & Create',
    'act.cancel': 'Cancel',
    'act.edit_72h': 'EDIT 72H',
    'act.edit': 'Edit Record',
    'act.delete': 'Delete',
    'act.update': 'Update Record',
    'act.confirm_delete': 'Are you sure you want to delete this record?',
    'act.transfer': 'Transfer',
    'tf.title': 'Transfer Between Accounts',
    'tf.from': 'From Account',
    'tf.to': 'To Account',
    'tf.amount': 'Amount to Transfer',
    'tf.execute': 'Execute Transfer',
    'tf.same_error': 'Select different accounts',
    'act.export': 'Export CSV',
    'act.reset': 'Factory Reset (Demo)',
    // Forms & Labels
    'lbl.amount': 'Amount',
    'lbl.desc': 'Description / Note',
    'lbl.category': 'Category',
    'lbl.account': 'Account',
    'lbl.date': 'Date',
    'lbl.type': 'Type',
    'lbl.person': 'Entity / Person',
    // Status
    'st.pending': 'PENDING',
    'st.paid': 'PAID',
    'st.partial': 'PARTIAL',
    'st.critical': 'CRITICAL',
    'st.ontrack': 'ON TRACK',
    'st.locked': 'LOCKED',
    // Empty
    'empty.generic': 'No data available in this sector.',
    // Settings
    'set.general': 'General Configuration',
    'set.vis': 'Visualization Protocol',
    'set.zone': 'Danger Zone',
    'set.lang': 'Language',
    'set.curr': 'Base Currency',
    'set.tz': 'Timezone',
    'set.theme': 'Theme Mode',
    'set.privacy': 'Privacy Mode',
    'set.cents': 'Precision (Show Cents)',
    'set.motion': 'Reduce Motion',
    // AI
    'ai.welcome': 'UFlow AI Assistant Online. How can I optimize your financial flow today?',
    'ai.placeholder': 'Ask anything or describe a transaction...',
    'ai.modal_title': 'Describe what you want to create',
    'ai.modal_placeholder': 'e.g. "I spent 50k on lunch yesterday" or "New goal for Travel 5M COP"',
    'ai.thinking': 'Processing Request...',
    'ai.generated': 'Generated Suggestion',
    // Credit Cards
    'cc.title': 'Credit Cards',
    'cc.add': 'Add Card',
    'cc.name': 'Card Name',
    'cc.limit': 'Credit Limit',
    'cc.used': 'Used',
    'cc.available': 'Available',
    'cc.cutoff': 'Cutoff',
    'cc.payment_day': 'Payment',
    'cc.mode_fixed': 'Fixed day',
    'cc.mode_relative': 'Relative',
    'cc.day_of_month': 'Day of month',
    'cc.days_before_payment': 'days before payment',
    'cc.days_after_cutoff': 'days after cutoff',
    'cc.charge': 'Register Charge',
    'cc.pay': 'Make Payment',
    'cc.pay_full': 'Pay total balance',
    'cc.utilization': 'Utilization',
    'cc.no_balance': 'No balance owed',
    'cc.confirm_delete': 'Are you sure you want to delete this card?',
    'cc.history': 'Card Movements',
    'cc.no_history': 'No movements recorded',
    // Shared Accounts
    'shared.title': 'Shared Accounts',
    'shared.create': 'Create Shared Account',
    'shared.join': 'Join with Code',
    'shared.join_placeholder': 'Enter invite code',
    'shared.name': 'Account Name',
    'shared.invite_code': 'Invite Code',
    'shared.copy_code': 'Copy Code',
    'shared.copied': 'Copied!',
    'shared.regenerate': 'Regenerate Code',
    'shared.members': 'Members',
    'shared.owner': 'Owner',
    'shared.member': 'Member',
    'shared.joined': 'Joined',
    'shared.leave': 'Leave Account',
    'shared.leave_confirm': 'Are you sure you want to leave this shared account?',
    'shared.transactions': 'Transactions',
    'shared.add_tx': 'Add Transaction',
    'shared.shared_expense': 'Shared expense',
    'shared.personal_expense': 'Personal expense',
    'shared.balance': 'Balance',
    'shared.contributed': 'Contributed',
    'shared.spent': 'Spent',
    'shared.share': 'Share',
    'shared.net': 'Net',
    'shared.no_transactions': 'No transactions yet',
    'shared.back': 'Back',
    'shared.empty': 'No shared accounts yet. Create one or join with a code.',
    'shared.delete_confirm': 'Are you sure you want to delete this transaction?',
  },
  es: {
    'nav.dashboard': 'Panel de Control',
    'nav.history': 'Historial',
    'nav.analytics': 'Analítica',
    'nav.accounts': 'Cuentas',
    'nav.debts': 'Riesgo y Deudas',
    'nav.goals': 'Metas',
    'nav.planner': 'Planificación',
    'nav.settings': 'Ajustes',
    'nav.ai': 'Asistente IA',
    'dash.total': 'Balance Total',
    'dash.available': 'Liquidez Disponible',
    'dash.relative': 'Balance Relativo',
    'dash.recent': 'Flujo de Datos',
    'dash.targets': 'Objetivos',
    'dash.risk': 'Evaluación de Riesgo',
    'dash.feedback': 'Feedback',
    'dash.feedback.placeholder': 'Escribe tu comentario, reporta un error o solicita una función...',
    'dash.feedback.send': 'Enviar',
    'dash.feedback.success': 'Feedback enviado. ¡Gracias!',
    'dash.feedback.error': 'No se pudo enviar. Intenta de nuevo.',
    'dash.feedback.teaser': '¿Comentarios o sugerencias?',
    'dash.burn': 'Tasa de Gasto Mensual',
    'dash.commands': 'Comandos Rápidos',
    'act.quick_input': 'Entrada Rápida',
    'act.create_ai': 'Crear con IA',
    'act.add': 'Agregar',
    'act.save': 'Guardar Registro',
    'act.confirm_create': 'Confirmar y Crear',
    'act.cancel': 'Cancelar',
    'act.edit_72h': 'EDITAR 72H',
    'act.edit': 'Editar Registro',
    'act.delete': 'Eliminar',
    'act.update': 'Actualizar Registro',
    'act.confirm_delete': '¿Estás seguro de que quieres eliminar este registro?',
    'act.transfer': 'Transferir',
    'tf.title': 'Transferencia entre Cuentas',
    'tf.from': 'Cuenta Origen',
    'tf.to': 'Cuenta Destino',
    'tf.amount': 'Monto a Transferir',
    'tf.execute': 'Ejecutar Transferencia',
    'tf.same_error': 'Selecciona cuentas diferentes',
    'act.export': 'Exportar CSV',
    'act.reset': 'Restaurar Fábrica (Demo)',
    'lbl.amount': 'Monto',
    'lbl.desc': 'Descripción / Nota',
    'lbl.category': 'Categoría',
    'lbl.account': 'Cuenta',
    'lbl.date': 'Fecha',
    'lbl.type': 'Tipo',
    'lbl.person': 'Entidad / Persona',
    'st.pending': 'PENDIENTE',
    'st.paid': 'PAGADO',
    'st.partial': 'PARCIAL',
    'st.critical': 'CRÍTICO',
    'st.ontrack': 'EN CAMINO',
    'st.locked': 'BLOQUEADO',
    'empty.generic': 'Sin datos disponibles en este sector.',
    'set.general': 'Configuración General',
    'set.vis': 'Protocolo de Visualización',
    'set.zone': 'Zona de Peligro',
    'set.lang': 'Idioma',
    'set.curr': 'Moneda Base',
    'set.tz': 'Zona Horaria',
    'set.theme': 'Tema',
    'set.privacy': 'Modo Privacidad',
    'set.cents': 'Precisión (Mostrar Centavos)',
    'set.motion': 'Reducir Movimiento',
    'ai.welcome': 'Asistente UFlow en línea. ¿Cómo puedo optimizar tu flujo financiero hoy?',
    'ai.placeholder': 'Pregunta lo que sea o describe una transacción...',
    'ai.modal_title': 'Describe qué quieres crear',
    'ai.modal_placeholder': 'ej. "Gasté 50k en almuerzo ayer" o "Nueva meta Viaje 5M COP"',
    'ai.thinking': 'Procesando Solicitud...',
    'ai.generated': 'Sugerencia Generada',
    'cc.title': 'Tarjetas de Crédito',
    'cc.add': 'Agregar Tarjeta',
    'cc.name': 'Nombre de Tarjeta',
    'cc.limit': 'Cupo Total',
    'cc.used': 'Usado',
    'cc.available': 'Disponible',
    'cc.cutoff': 'Corte',
    'cc.payment_day': 'Pago',
    'cc.mode_fixed': 'Día fijo',
    'cc.mode_relative': 'Relativo',
    'cc.day_of_month': 'Día del mes',
    'cc.days_before_payment': 'días antes del pago',
    'cc.days_after_cutoff': 'días después del corte',
    'cc.charge': 'Registrar Cargo',
    'cc.pay': 'Registrar Pago',
    'cc.pay_full': 'Pagar todo el saldo',
    'cc.utilization': 'Utilización',
    'cc.no_balance': 'Sin saldo pendiente',
    'cc.confirm_delete': '¿Estás seguro de que quieres eliminar esta tarjeta?',
    'cc.history': 'Movimientos de Tarjeta',
    'cc.no_history': 'Sin movimientos registrados',
    // Shared Accounts
    'shared.title': 'Cuentas Compartidas',
    'shared.create': 'Crear Cuenta Compartida',
    'shared.join': 'Unirse con Código',
    'shared.join_placeholder': 'Ingresa código de invitación',
    'shared.name': 'Nombre de la Cuenta',
    'shared.invite_code': 'Código de Invitación',
    'shared.copy_code': 'Copiar Código',
    'shared.copied': '¡Copiado!',
    'shared.regenerate': 'Regenerar Código',
    'shared.members': 'Miembros',
    'shared.owner': 'Dueño',
    'shared.member': 'Miembro',
    'shared.joined': 'Se unió',
    'shared.leave': 'Salir de la Cuenta',
    'shared.leave_confirm': '¿Estás seguro de que quieres salir de esta cuenta compartida?',
    'shared.transactions': 'Transacciones',
    'shared.add_tx': 'Agregar Transacción',
    'shared.shared_expense': 'Gasto compartido',
    'shared.personal_expense': 'Gasto personal',
    'shared.balance': 'Balance',
    'shared.contributed': 'Aportó',
    'shared.spent': 'Gastó',
    'shared.share': 'Parte',
    'shared.net': 'Neto',
    'shared.no_transactions': 'Sin transacciones aún',
    'shared.back': 'Volver',
    'shared.empty': 'Sin cuentas compartidas. Crea una o únete con un código.',
    'shared.delete_confirm': '¿Estás seguro de que quieres eliminar esta transacción?',
  }
};

export const DEMO_ACCOUNTS: Account[] = [
  { id: '1', name: 'Main Wallet', type: 'individual', currency: 'COP' },
  { id: '2', name: 'Bank Reserve', type: 'individual', currency: 'USD' },
  { id: '3', name: 'Apt 402 Shared', type: 'shared', currency: 'COP', members: ['You', 'Ana'] },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  { id: 't1', type: 'income', amount: 4500000, currency: 'COP', accountId: '1', category: 'Salary', note: 'Monthly payroll', date: new Date().toISOString(), createdAt: Date.now() },
  { id: 't2', type: 'expense', amount: 1200000, currency: 'COP', accountId: '3', category: 'Rent', note: 'November Rent', date: new Date().toISOString(), createdAt: Date.now() - 80000000 }, // Old
  { id: 't3', type: 'expense', amount: 45000, currency: 'COP', accountId: '1', category: 'Food', note: 'Lunch w/ team', date: new Date().toISOString(), createdAt: Date.now() },
  { id: 't4', type: 'expense', amount: 15, currency: 'USD', accountId: '2', category: 'Subscriptions', note: 'Netflix', date: new Date().toISOString(), createdAt: Date.now() },
  { id: 't5', type: 'adjustment', amount: -50000, currency: 'COP', accountId: '1', category: 'Misc', note: 'Cash lost', date: new Date().toISOString(), createdAt: Date.now() },
];

export const DEMO_DEBTS: Debt[] = [
  { id: 'd1', person: 'Carlos M.', type: 'owes_me', totalAmount: 200000, currency: 'COP', status: 'pending', payments: [], createdAt: new Date().toISOString() },
  { id: 'd2', person: 'Visa Credit', type: 'i_owe', totalAmount: 1500, currency: 'USD', status: 'partial', payments: [{id: 'p1', amount: 500, date: new Date().toISOString()}], createdAt: new Date().toISOString() },
];

export const DEMO_CREDIT_CARDS: CreditCard[] = [
  { id: 'cc1', name: 'Visa Gold', creditLimit: 5000000, usedAmount: 1800000, currency: 'COP', cutoffDay: 15, cutoffMode: 'fixed', paymentDay: 5, paymentMode: 'fixed', createdAt: new Date().toISOString() },
  { id: 'cc2', name: 'Mastercard Black', creditLimit: 3000, usedAmount: 850, currency: 'USD', cutoffDay: 20, cutoffMode: 'fixed', paymentDay: 10, paymentMode: 'relative', createdAt: new Date().toISOString() },
];

export const DEMO_GOALS: Goal[] = [
  { id: 'g1', name: 'Emergency Fund', targetAmount: 10000000, currentAmount: 2500000, currency: 'COP', status: 'active', contributions: [] },
  { id: 'g2', name: 'New Mac Studio', targetAmount: 2000, currentAmount: 1200, currency: 'USD', status: 'active', contributions: [] },
];

export const DEMO_PLAN_ITEMS: PlanItem[] = [
  { id: 'p1', type: 'income', concept: 'Salary', planned: 5000000, real: 0, month: '2026-02', currency: 'COP' },
  { id: 'p2', type: 'expense', concept: 'Food', planned: 800000, real: 0, month: '2026-02', currency: 'COP' },
  { id: 'p3', type: 'expense', concept: 'Transport', planned: 300000, real: 0, month: '2026-02', currency: 'COP' },
];